### ISSUE TITLE
HM调用python训练好的模型有什么好方法吗？

### ISSUE THREAD

**Issue by WigenTang** [tianyili2017/HEVC-Complexity-Reduction#10]
因为用python训练网络比较方便，TensorFlow，pytorch等都可以用，但是怎样把训练好的模型导入HM里做预测好像都不是很方便，而且很慢，请问您用过什么比较有效的方法吗？

谢谢， 祝好！

**Comment by tianyili2017** [comment]
您好，
因为我们的研究主要是算法，所以就先用比较友好的Python进行实现，也就是把Python版的神经网络和C++版的HM间接连接。关于直接连接，如何把神经网络嵌入HM，我们了解的还比较少，您可以尝试下把Python网络模型转换成C或C++版本的深度学习库支持的格式，再嵌入HM里。谢谢！
